GET http://localhost:3001/api/notes/

###
Get http://localhost:3001/api/notes/613b5faa1c8f2443ef414ebd

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
      "content": "Sneppy True",
      "important": true
}

###
PUT http://localhost:3001/api/notes/613b87851323a30d74b6a0ea
content-type: application/json

{
      "content": "Sneppy True",
      "important": true
}

###
DELETE http://localhost:3001/api/notes/613b87c81323a30d74b6a0ef